### ISSUE TITLE
Source Address may have Preceding Null

### ISSUE THREAD

**Issue by coolacid** [python-aprs/ax253#6]
When using a Kenwood D700's TNC in Kiss mode the source address is preceded by a Null Byte, this fails the address check. Not sure if this is the best place, of the x25 project, but that project doesn't have issues available. 

To work around this issue I just use an `.lstrip("\0")`.

**Comment by masenf** [comment]
Thanks for reporting this issue.

I have a D710G that I could fire up and test with when I get a chance, but if you have a binary capture of the KISS data that I could use for regression testing that would be easier.

I'm also trying to understand what exact error you are seeing, is it `"ax25 address must be 7 bytes, got {}".format(len(ax25_address))` or something else?

**Comment by coolacid** [comment]
Thanks for the super quick reply!

Here's the packet: 
`b'\x00\xac\x8af\xb2\x86\x82\xe4\xac\x8af\xb2\x86\x82c?'`

and the trace:

```
Traceback (most recent call last):
  File "/home/Repos/LSR/BPQ/src/interfaces/kiss.py", line 37, in cbFrame
    data = ax253.Frame.from_bytes(frame)
  File "/home/Repos/LSR/BPQ/dev/lib/python3.10/site-packages/ax253/frame.py", line 157, in from_bytes
    destination = Address.from_bytes(ax25_bytes[:7])
  File "/home/Repos/LSR/BPQ/dev/lib/python3.10/site-packages/ax253/address.py", line 60, in from_bytes
    return cls(**init_kwargs)
  File "<attrs generated init ax253.address.Address>", line 8, in __init__
    __attr_validator_callsign(self, __attr_callsign, self.callsign)
  File "/home/Repos/LSR/BPQ/dev/lib/python3.10/site-packages/ax253/address.py", line 22, in valid_callsign
    raise ValueError("{!r} does not match {!r}".format(value, VALID_CALLSIGN_REX))
ValueError: b'\x00VE3YC' does not match re.compile(b'^[A-Z0-9]+$')
```

The call sign should have been `VE3YCA` and the leading Null in the packet breaks it.

**Comment by masenf** [comment]
Ah okay, so sounds like the _entire packet_ has a leading null byte, maybe Kenwood was using that as packet delimiter (despite being out of spec...).

As for the radio mode, I'm assuming you're in packet mode and pulling the bytes via the `kiss.SerialKISS` interface?

Have you noticed any other packet decode issues with other software (such as linux ax.25 stack)?

I can probably get this patched up in the next day or two.

**Comment by coolacid** [comment]
Yep, `kiss.SerialKISS` Sorry, I'm normally better with my issues, but was not at my PC when writing them. 

We have LinBPQ running on some D700's at our repeater site in KISS mode with no issues. I did a quick look through it's code, but nothing jumped out as a hack to fix it.

**Comment by masenf** [comment]
@coolacid how are you instantiating `kiss.SerialKISS`?

I think you need to pass `strip_df_start=True` when using the D700, which basically does your lstrip workaround.

Something like:

```
k = kiss.SerialKISS('/dev/ttyUSB0', 1200, strip_df_start=True)
```

I think passing `strip_df_start` will resolve the problem, but I will leave this issue open to update the README and help the next person struggling over this.

**Comment by coolacid** [comment]
Yep, that's exactly it. Thanks.
